// NLWeb endpoint for VoiceLogPro (Microsoft Copilot / Bing Chat)
// Auto-generated by growth engine

const content = [
  {
    "@type": "Question",
    "name": "How does voice daily logging work?",
    "acceptedAnswer": "VoiceLogPro converts your spoken field report into a structured, compliant construction daily log with categories for work performed, weather, crew, equipment, delays, and safety incidents.",
    "url": "https://voicelogpro.com/#faq"
  },
  {
    "@type": "Question",
    "name": "Is the daily log OSHA compliant?",
    "acceptedAnswer": "Yes, VoiceLogPro templates follow OSHA documentation requirements including date, weather conditions, work activities, safety meetings, and incidents.",
    "url": "https://voicelogpro.com/#faq"
  },
  {
    "@type": "Question",
    "name": "Can I export the daily log to PDF?",
    "acceptedAnswer": "Yes, VoiceLogPro exports to PDF, CSV, and integrates with Procore, Autodesk Construction Cloud, and PlanGrid.",
    "url": "https://voicelogpro.com/#faq"
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  
  const query = req.method === 'POST' 
    ? (req.body?.query || '').toLowerCase()
    : (req.query.query || '').toLowerCase();
  
  // Search FAQs
  const matches = query 
    ? content.filter(c => 
        c.name.toLowerCase().includes(query) || 
        c.acceptedAnswer.toLowerCase().includes(query)
      )
    : content;
  
  return res.json({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'name': 'VoiceLogPro Knowledge Base',
    'description': 'Voice-powered construction daily log app. Dictate your daily report hands-free and generate compliant, professional logs in seconds.',
    'numberOfItems': matches.length,
    'itemListElement': matches
  });
}
